[features]
seeds = false
skip-lint = false
[programs.devnet]
saving_app = "F6z12TSKZsqDymiDGShcoLhPjcRTHBTt9B4TYv7cyEsJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vlnv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
